### PR TITLE
Add a version of dfscomp to AccordDaTools

### PR DESCRIPTION
**Pull request by ewhelan**
Potential to make FORTRAN a little less hard-coded!

### CODE REVIEW

**Comment by ewhelan** [comment]
Hi @dschoenach 

I am just taking a look at the dfscomp FORTRAN. I am wondering would this be a good opportunity to make this a little more flexible? Would it make sense to loop through all possible code types rather than using a hard-coded set of observations (25 at the moment).

Could we use IFS _codetypes_? [https://apps.ecmwf.int/odbgov/codetype/](https://apps.ecmwf.int/odbgov/codetype/)

**Comment by ewhelan** [comment]
... and satellite identifiers.

**Comment by dschoenach** [comment]
> 

Yes, that is a good idea. Probably also good to write the codetype and the satellite ids, and all the others which are used in the end to distinguish, to this dfs.dat.

**Comment by ewhelan** [comment]
Or even satellite instrument. See what Météo France do [http://www.meteo.fr/special/minisites/monitoring/DFS/dfs.html](http://www.meteo.fr/special/minisites/monitoring/DFS/dfs.html)

**Comment by ewhelan** [comment]
Think I have brought this far enough for now. @dschoenach : if you are happy I can merge.

The plotting tool produces a bar-chart and a pie-chart. Relative DFS to be added at a later stage.

**Review by dschoenach — COMMENTED** [review]
Looks good.

**Pull request merged**
