### PR TITLE
Festat standalone is now added

### PR DESCRIPTION
**Pull request by swapanmallicksmhi**

### CODE REVIEW

**Comment by ewhelan** [comment]
Thanks for this @swapanmallicksmhi. I will try to take a look ASAP.

**Comment by roelstappers** [comment]
Hi @swapanmallicksmhi,

Just a suggestion feel free to ignore if you don't have time. It could be good to split the script in two step. One script to prepare the working directory with the symlinks and a second scripts that submits the job to the HPC.  

For the first step I would use a language that is a bit better at handling dates (and arrays) than bash. Either python or even better julia (it's available on Atos with `module load julia`). 

E.g. something like (untested) 

```julia
using Dates

SCRATCH=ENV["SCRATCH"]
EXP="myexp"
HM_DATA="$SCRATCH/hm_home/$EXP/"


dtgbeg=DateTime(2022,01,03,00)
dtgend=DateTime(2023,01,30,00)
dtgstep=Day(6) 
dtgrange = dtgbeg:dtgstep:dtgend

filename = "ICMSHHARM+0006"

subdirs = Dates.format.(dtgrange,"yyyy/mm/dd/HH")
mbrs = lpad.(1:9,3,"0")  # ["001", "002"  ... "009"]

targets = [joinpath(HM_DATA,sd,"mbr",mbr,filename) for sd in subdirs for mbr in mbrs] 

for (index,target) in enumerate(targets) 
    i3 = lpad(index,3,"0")
    symlink(target,"ICMSHHARM+0$i3") 
end 

```

**Comment by swapanmallicksmhi** [comment]
Hi @roelstappers, Sure, I will try to convert the script in python or Julia. And will to the test first.

**Review by ewhelan — COMMENTED** [review]
Hi @swapanmallicksmhi 

Taking a look now. First off, your PR branch is develop. When we get you code in this will cause problems for your fork. I think you have two options:
1. Persist with the `develop` PR and fix your fork afterwards
2. Close this PR and open a new PR with a newly named branch created from develop.


Opinions @roelstappers ? I know you have dealt with similar in the past.

**Comment by roelstappers** [comment]
No strong opinions both work. Maybe now continue with using `develop` and after the merge fix this. A colleague had the issue and he could  fix his develop branch by clicking "sync fork" after his PR was merged, i.e. that sync removed the commits.

**Comment by ewhelan** [comment]
> No strong opinions both work. Maybe now continue with using `develop` and after the merge fix this. A colleague had the issue and he could fix his develop branch by clicking "sync fork" after his PR was merged, i.e. that sync removed the commits.

Thanks @roelstappers. I did not realize this was possible. Let's stick with this PR so ...

**Comment by swapanmallicksmhi** [comment]
Hi @ewhelan and @roelstappers,

Thank you for all the comments.
Is it ok if I follow the first option?
Also I need your comments on this python and bash script.
Now the script is divided with two parts as suggested by @roelstappers . 
First python script (festat_S1.py) is to arrange input FA file and is work fine in Atos.

The second part is to submit the job in Atos. 
Unfortunately the python script for the second one do not work at Atos.
So I keep the second part in bash only.
Please suggest on this.

Below are the two script I attached.

festat_S1.py----->
#
import os
from datetime import datetime, timedelta

#---------INPUT NEEDED-----------
EXP    = "SURF_CARRA2_CY46"              # Change the experiment name here
dtgbeg =  datetime(2022, 1, 15, 00)       # Change Start date 
dtgend =  datetime(2022, 2, 12, 18)       # Change End date
#--------------------------------
#
cycl =  timedelta(hours=6)                # Assimilation cycle at 00 06 12 and 18 UTC
SCRATCH = os.environ['SCRATCH']
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
TMPOUT  = os.path.join(SCRATCH,'tmp_festat') # Working directory 'tmp_festat' 
os.makedirs(TMPOUT, mode=0o755, exist_ok=True)
os.chdir(TMPOUT)
ens_mem=range(1,10)                       # Ensemble member (ens1,ens2.....,ens9)
filename = "ICMSHHARM+0006"               # 6 hour forecast FA file
fnumber=1
#
while dtgbeg <= dtgend:
    YY=dtgbeg.isoformat()[0:4]
    MM=dtgbeg.isoformat()[5:7]
    DD=dtgbeg.isoformat()[8:10]
    HH=dtgbeg.isoformat()[11:13]
    for mm in ens_mem:
        mem='mbr00'.ljust(6,str(mm))
        target = os.path.join(HM_DATA, YY, MM, DD, HH, mem, filename)
        print(target)
        #
        if   ( fnumber <= 9 ):
            filelink = filename[:-1]+str(fnumber)
        elif ( fnumber >= 10 and fnumber <= 99 ):
            filelink = filename[:-2]+str(fnumber)
        elif ( fnumber >= 100 and fnumber <= 999 ):
            filelink = filename[:-3]+str(fnumber)
        else:
            break
        #
        if os.path.isfile(filelink):
           os.remove(filelink)
        os.symlink(target ,filelink)
        fnumber += 1

    dtgbeg += cycl
#
print(TMPOUT)
quit()


festst_S2.job------>

#!/bin/bash
#SBATCH --cpus-per-task=8
#SBATCH --error=festat.log
#SBATCH --job-name=FESTAT
#SBATCH --nodes=37
#SBATCH --output=festat.log
#SBATCH --qos=np
#SBATCH --ntasks-per-node=27
#SBATCH --time=02:00:00
#
#
export MPPEXEC="srun"
export NPROC=999
export NPROCX=1
export NPROCY=1
export OMP_MAX_ACTIVE_LEVELS=1
export OMP_NUM_THREADS=8
export OMP_STACKSIZE=256M
eojcmd=""
ulimit -S -s unlimited || ulimit -s
ulimit -S -m unlimited || ulimit -m
ulimit -S -d unlimited || ulimit -d
set -e 
##
EXP=SURF_CARRA2_CY46
ENV=${HOME}/hm_home/$EXP
# Build the namelist
cat > fort.4 << EOF
&NAMFESTAT
  NCASES=$NPROC,
  LSTABAL=.true.,
  LANAFBAL=.true., 
  LELAM=.TRUE., 
  CNAME='ICMSHHARM+0', 
  NFRGRP=9,
  NPRINTLEV=0,
  LOZONE=.FALSE.,
  LOZBAL=.FALSE.,
  LUVBAL=.FALSE.,
  OUTBAL='stab.bal'
  OUTCVT='stab.cvt',
  OUTCVU='stab.cv',
/
EOF
source ${ENV}/Env_system
srun FESTAT  || exit
#
trap - 0
exit

**Comment by roelstappers** [comment]
@swapanmallicksmhi To make the code more readable can you edit your message and put your code between triple backticks  like this: 
````
```python
example code 
```
````

Then it will look like this

```python
example code 
```

**Comment by swapanmallicksmhi** [comment]
Thanks @roelstappers 

``` 
Python (festat_S1.py)
#
import os
from datetime import datetime, timedelta

#---------INPUT NEEDED-----------
EXP    = "SURF_CARRA2_CY46"              # Change the experiment name here
dtgbeg =  datetime(2022, 1, 15, 00)       # Change Start date 
dtgend =  datetime(2022, 2, 12, 18)       # Change End date
#--------------------------------
#
cycl =  timedelta(hours=6)                # Assimilation cycle at 00 06 12 and 18 UTC
SCRATCH = os.environ['SCRATCH']
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
TMPOUT  = os.path.join(SCRATCH,'tmp_festat') # Working directory 'tmp_festat' 
os.makedirs(TMPOUT, mode=0o755, exist_ok=True)
os.chdir(TMPOUT)
ens_mem=range(1,10)                       # Ensemble member (ens1,ens2.....,ens9)
filename = "ICMSHHARM+0006"               # 6 hour forecast FA file
fnumber=1
#
while dtgbeg <= dtgend:
    YY=dtgbeg.isoformat()[0:4]
    MM=dtgbeg.isoformat()[5:7]
    DD=dtgbeg.isoformat()[8:10]
    HH=dtgbeg.isoformat()[11:13]
    for mm in ens_mem:
        mem='mbr00'.ljust(6,str(mm))
        target = os.path.join(HM_DATA, YY, MM, DD, HH, mem, filename)
        print(target)
        #
        if   ( fnumber <= 9 ):
            filelink = filename[:-1]+str(fnumber)
        elif ( fnumber >= 10 and fnumber <= 99 ):
            filelink = filename[:-2]+str(fnumber)
        elif ( fnumber >= 100 and fnumber <= 999 ):
            filelink = filename[:-3]+str(fnumber)
        else:
            break
        #
        if os.path.isfile(filelink):
           os.remove(filelink)
        os.symlink(target ,filelink)
        fnumber += 1

    dtgbeg += cycl
#
print(TMPOUT)
quit()

```


```bash ( festst_S2.job)
#!/bin/bash
#SBATCH --cpus-per-task=8
#SBATCH --error=festat.log
#SBATCH --job-name=FESTAT
#SBATCH --nodes=37
#SBATCH --output=festat.log
#SBATCH --qos=np
#SBATCH --ntasks-per-node=27
#SBATCH --time=02:00:00
#
#
export MPPEXEC="srun"
export NPROC=999
export NPROCX=1
export NPROCY=1
export OMP_MAX_ACTIVE_LEVELS=1
export OMP_NUM_THREADS=8
export OMP_STACKSIZE=256M
eojcmd=""
ulimit -S -s unlimited || ulimit -s
ulimit -S -m unlimited || ulimit -m
ulimit -S -d unlimited || ulimit -d
set -e 
##
EXP=SURF_CARRA2_CY46
ENV=${HOME}/hm_home/$EXP
# Build the namelist
cat > fort.4 << EOF
&NAMFESTAT
  NCASES=$NPROC,
  LSTABAL=.true.,
  LANAFBAL=.true., 
  LELAM=.TRUE., 
  CNAME='ICMSHHARM+0', 
  NFRGRP=9,
  NPRINTLEV=0,
  LOZONE=.FALSE.,
  LOZBAL=.FALSE.,
  LUVBAL=.FALSE.,
  OUTBAL='stab.bal'
  OUTCVT='stab.cvt',
  OUTCVU='stab.cv',
/
EOF
source ${ENV}/Env_system
srun FESTAT  || exit
#
trap - 0
exit

```

**Comment by swapanmallicksmhi** [comment]
Both of them work well one after another in Atos.

**Comment by roelstappers** [comment]
Thanks Swapan!  Using Python for `festat_S1`  has made it much more readable I think. For the second step you can just keep that in bash. It won't  benefit from using a more powerful language and is readable as is. 

Some minor remarks, not a python user myself (preferring Julia) but I expect that in Python there must be better construction for 
```python 
  if   ( fnumber <= 9 ):
            filelink = filename[:-1]+str(fnumber)
        elif ( fnumber >= 10 and fnumber <= 99 ):
            filelink = filename[:-2]+str(fnumber)
        elif ( fnumber >= 100 and fnumber <= 999 ):
            filelink = filename[:-3]+str(fnumber)
        else:
            break
```

e.g. make it a oneline using something like `lpad(fnumber,3,"0")` to pad numbers with zero on the left like in the Julia example. 
And for this: 
```python
    YY=dtgbeg.isoformat()[0:4]
    MM=dtgbeg.isoformat()[5:7]
    DD=dtgbeg.isoformat()[8:10]
    HH=dtgbeg.isoformat()[11:13]
```

There must be some proper date time functions to extract year month date. Also I would call the loop index `dtg` instead of `dtgbeg`

**Comment by swapanmallicksmhi** [comment]
Okay, here is my Python script, crafted to optimize functionality while taking into account all minor suggestions and comments by @roelstappers 
'''
python festat_S1.py
#
import os
from datetime import datetime, timedelta

#---------INPUT STAFF-----------
EXP    = "SURF_CARRA2_CY46"                            # Change the experiment name here
dtg    = datetime.strptime('2022011500', '%Y%m%d%H')   # Change Start date
dtgend = datetime.strptime('2022021218', '%Y%m%d%H')   # Change End date
#--------------------------------
cycl =  timedelta(hours=6)                             # Assimilation cycle at 00 06 12 and 18 UTC
SCRATCH = os.environ['SCRATCH']
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
TMPOUT  = os.path.join(SCRATCH,'tmp_festat11')         # Working directory 'tmp_festat' 
os.makedirs(TMPOUT, mode=0o755, exist_ok=True)
os.chdir(TMPOUT)
ens_mem=range(1,10)                                    # Ensemble member (ens1,ens2.....,ens9)
filename = "ICMSHHARM+0006"                            # 6 hour forecast FA file
fnumber=1
#
while dtg <= dtgend:
    #
    YY = str(dtg.year).ljust(4, '0')
    MM = str(dtg.month).zfill(2)
    DD = str(dtg.day).zfill(2)
    HH = str(dtg.hour).zfill(2)
    # 
    for mm in ens_mem:
        mem='mbr00'.ljust(6,str(mm))
        target = os.path.join(HM_DATA, YY, MM, DD, HH, mem, filename)
        #print(target)
        #
        filecond =  {fnumber <= 9: filename[:-1]+str(fnumber),
            10  <=  fnumber <= 99: filename[:-2]+str(fnumber),
           100  <= fnumber <= 999: filename[:-3]+str(fnumber)}
        filelink = filecond.get(True,None)
        if os.path.isfile(str(filelink)):
              os.remove(str(filelink))
        os.symlink(str(target),str(filelink))
        print(str(filelink),str(target))
        fnumber += 1
    dtg += cycl
#
print(TMPOUT)
quit()
'''

**Comment by swapanmallicksmhi** [comment]
Okay, here is my Python script, crafted to optimize functionality while taking into account all minor suggestions and comments by @roelstappers

```
python festat_S1.py
import os
from datetime import datetime, timedelta

#---------INPUT STAFF-----------
EXP    = "SURF_CARRA2_CY46"                            # Change the experiment name here
dtg    = datetime.strptime('2022011500', '%Y%m%d%H')   # Change Start date
dtgend = datetime.strptime('2022021218', '%Y%m%d%H')   # Change End date
#--------------------------------
#
cycl =  timedelta(hours=6)                             # Assimilation cycle at 00 06 12 and 18 UTC
SCRATCH = os.environ['SCRATCH']
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
HM_DATA = os.path.join(SCRATCH,'hm_home',EXP,'archive')
TMPOUT  = os.path.join(SCRATCH,'tmp_festat11')         # Working directory 'tmp_festat' 
os.makedirs(TMPOUT, mode=0o755, exist_ok=True)
os.chdir(TMPOUT)
ens_mem=range(1,10)                                    # Ensemble member (ens1,ens2.....,ens9)
filename = "ICMSHHARM+0006"                            # 6 hour forecast FA file
fnumber=1
#
while dtg <= dtgend:
    #
    YY = str(dtg.year).ljust(4, '0')
    MM = str(dtg.month).zfill(2)
    DD = str(dtg.day).zfill(2)
    HH = str(dtg.hour).zfill(2)
    # 
    for mm in ens_mem:
        mem='mbr00'.ljust(6,str(mm))
        target = os.path.join(HM_DATA, YY, MM, DD, HH, mem, filename)
        #print(target)
        #
        filecond =  {fnumber <= 9: filename[:-1]+str(fnumber),
            10  <=  fnumber <= 99: filename[:-2]+str(fnumber),
           100  <= fnumber <= 999: filename[:-3]+str(fnumber)}
        filelink = filecond.get(True,None)
        if os.path.isfile(str(filelink)):
              os.remove(str(filelink))
        os.symlink(str(target),str(filelink))
        print(str(filelink),str(target))
        fnumber += 1
    dtg += cycl
#
print(TMPOUT)
quit()

```

**Pull request closed without merging**
