### PR TITLE
Documentation using github pages

### PR DESCRIPTION
**Pull request by roelstappers**
This mimics what is done in Hirlam/Harmonie and ACCORD-NWP/DAVAI-Env

The `documentation.yml` github action will create html pages from the markdown files in `docs/src` and these will get deployed to the gh-pages branch. Difference with Hirlam/Harmonie is that in Harmonie we deploy the html pages to an external repo (Hirlam/HarmonieSystemDocumentation) while here the gh-pages branch will be in ACCORD-NWP/AccordDaTools . Once the html are deployed Github should start a webserver automatically.

### CODE REVIEW

**Comment by roelstappers** [comment]
@ewhelan The github action triggered fine https://github.com/ACCORD-NWP/AccordDaTools/actions/runs/7625761640/job/20770730717. 

But as you can see in the logs for security reasons the Documenter tool will not deploy html pages if the PR originates from an other repository, i.e as in this case from my fork. So there is no preview of the docs like we have in Hirlam/Harmonie.  I expect that if you merge the PR all should be fine and the gh-pages created.

**Review by ewhelan — APPROVED** [review]
Thanks for this @roelstappers 

Let's take this as it is now and we can correct/iterate if need be.

**Comment by roelstappers** [comment]
@ewhelan The gh-pages branch got created  https://github.com/ACCORD-NWP/AccordDaTools/tree/gh-pages. 
but maybe there is a manual step need. Do you see anything in https://github.com/ACCORD-NWP/AccordDaTools/settings/pages to specify that it should serve the html pages from the gh-pages branch? I thought that was automatic

**Comment by ewhelan** [comment]
No. I do not see anything there. Could there be any ACCORD-NWP settings we might need adjusted by Alexandre?

**Comment by roelstappers** [comment]
This is how it should look  (from Hirlam/HarmonieSystemDocumentation). 

image

But could be indeed that only @AlexandreMary is allowed to change this

**Comment by AlexandreMary** [comment]
Hi,
Eoin I just switched your role to admin of the repo, so you should be able to set more things up.

**Comment by ewhelan** [comment]
> Hi, Eoin I just switched your role to admin of the repo, so you should be able to set more things up.

Thanks @AlexandreMary .

**Comment by roelstappers** [comment]
https://accord-nwp.github.io/AccordDaTools/dev/

**Comment by ewhelan** [comment]
Thanks @roelstappers and @AlexandreMary for all the help. The ball is back in my court now! 🎾

**Pull request merged**
